version: '3.8'

x-content-volumes: &cont_vols
    - static_content:/home/app/web/project/static
    - media_content:/home/app/web/project/media
x-db-secrets: &db_secrets
    - psql_user
    - psql_pass
    - psql_dbname
services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_DB_FILE=/run/secrets/psql_dbname
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pass
    secrets: *db_secrets
    healthcheck:
      test: pg_isready -U myuser -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    image: python
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes: *cont_vols
    expose:
      - 5000
    env_file:
      - ./.env.prod
#    depends_on:
#      db:
#        condition: service_healthy
    # web needs those as well so we can parametize the DATABASE_CONNEXION URL
    secrets: *db_secrets
  nginx:
    build: ./services/nginx
    image: nginx
    volumes: *cont_vols
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_content:
  media_content:

# external - assumes that you used docker secret create to create those named secrets
secrets:
  psql_user:
    file: ./psql_user.txt
#    external: true
  psql_pass:
    file: ./psql_pass.txt
  #    external: true
  psql_dbname:
    file: ./psql_dbname.txt
#    external: true