version: '3.8'

services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    image: python
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_content:/home/app/web/project/static
      - media_content:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    image: nginx
    volumes:
      - static_content:/home/app/web/project/static
      - media_content:/home/app/web/project/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_content:
  media_content: