version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes: 
      - ./services/web:/usr/src/app
    ports:
      - 80:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=db_dev
volumes:
  postgres_data: